export const ADD_TODO = "ADD_TODO"
export const TOGGLE_TODO = "TOGGLE_TODO"
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER"


export const SET_INPUT_VALUE = "SET_INPUT_VALUE"


export const RECEIVE_TODOS = "RECEIVE_TODOS"

